### ISSUE TITLE
Need support for Firebase 8 

### ISSUE THREAD

**Issue by shamilovtim** [segment-integrations/analytics-ios-integration-firebase#78] opened 2021-06-21 17:26 UTC
Hello, could you please update support for Firebase 8? Thank you

**Comment by rlindner** [comment] 2021-07-14 14:38
Duplicate of https://github.com/segment-integrations/analytics-ios-integration-firebase/issues/72

**Comment by shamilovtim** [comment] 2021-07-16 17:10
Can you please respond @bsneed

**Comment by chih98** [comment] 2021-09-17 20:19
+1 to this

**Comment by shamilovtim** [comment] 2021-09-17 22:16
@bsneed we've filed a ticket and asked on here as well. any ETA?

**Comment by shamilovtim** [comment] 2021-10-01 07:13
Any ETA? 

@bsneed @pmunin @knksmith57

**Comment by pmunin** [comment] 2021-10-01 15:41
@shamilovtim, sorry did I miss something or, was I mentioned by mistake? :)

**Comment by shamilovtim** [comment] 2021-10-05 14:54
@pmunin How do we get you guys to upgrade Firebase in this integration? We've had people open tickets in support, and have opened dev to dev tickets here only to be ignored.

**Comment by pmunin** [comment] 2021-10-05 19:01
@shamilovtim I'm a new guy, this is my 7th day, still doing onboarding, not sure how I to answer this yet

**Comment by bsneed** [comment] 2021-10-05 22:02
Closing since it's a duplicated and random people are getting tagged now.  Please follow #72

**Closed by bsneed** 2021-10-05 22:02 UTC
